name: Publish Docker Image

on:
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@main
    - name: Publish to Registry
      uses: elgohr/Publish-Docker-Github-Action@main
      with:
        name: traversaro/gitpod-ubuntu-20.04
        username: ${{ github.actor }}
        password: ${{ secrets.GH_TOKEN }}
        workdir: dockerfiles
        registry: ghcr.io
